using System;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.calc.marketdata
{

	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using TypedMetaBean = org.joda.beans.TypedMetaBean;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using LightMetaBean = org.joda.beans.impl.light.LightMetaBean;

	using ReferenceData = com.opengamma.strata.basics.ReferenceData;
	using MarketDataId = com.opengamma.strata.data.MarketDataId;
	using MarketDataBox = com.opengamma.strata.data.scenario.MarketDataBox;

	/// <summary>
	/// A market data filter that matches a specific identifier.
	/// </summary>
	/// @param <T>  the type of the market data handled by the filter </param>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(style = "light", constructorScope = "package") final class IdFilter<T> implements MarketDataFilter<T, com.opengamma.strata.data.MarketDataId<T>>, org.joda.beans.ImmutableBean
	internal sealed class IdFilter<T> : MarketDataFilter<T, MarketDataId<T>>, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final com.opengamma.strata.data.MarketDataId<T> id;
		private readonly MarketDataId<T> id;

	  //-------------------------------------------------------------------------
	  public Type MarketDataIdType
	  {
		  get
		  {
			return id.GetType();
		  }
	  }

	  public bool matches(MarketDataId<T> marketDataId, MarketDataBox<T> marketData, ReferenceData refData)
	  {
		return marketDataId.Equals(id);
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code IdFilter}.
	  /// </summary>
	  private static readonly MetaBean META_BEAN = LightMetaBean.of(typeof(IdFilter), MethodHandles.lookup(), new string[] {"id"}, new object[0]);

	  /// <summary>
	  /// The meta-bean for {@code IdFilter}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static MetaBean meta()
	  {
		return META_BEAN;
	  }

	  static IdFilter()
	  {
		MetaBean.register(META_BEAN);
	  }

	  /// <summary>
	  /// Creates an instance. </summary>
	  /// <param name="id">  the value of the property, not null </param>
	  internal IdFilter(MarketDataId<T> id)
	  {
		JodaBeanUtils.notNull(id, "id");
		this.id = id;
	  }

//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @Override @SuppressWarnings("unchecked") public org.joda.beans.TypedMetaBean<IdFilter<T>> metaBean()
	  public override TypedMetaBean<IdFilter<T>> metaBean()
	  {
		return (TypedMetaBean<IdFilter<T>>) META_BEAN;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the identifier that is matched by this filter. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public MarketDataId<T> Id
	  {
		  get
		  {
			return id;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: IdFilter<?> other = (IdFilter<?>) obj;
		  IdFilter<object> other = (IdFilter<object>) obj;
		  return JodaBeanUtils.equal(id, other.id);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(id);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(64);
		buf.Append("IdFilter{");
		buf.Append("id").Append('=').Append(JodaBeanUtils.ToString(id));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}