using System;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.calc.marketdata
{

	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using TypedMetaBean = org.joda.beans.TypedMetaBean;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using LightMetaBean = org.joda.beans.impl.light.LightMetaBean;

	using ReferenceData = com.opengamma.strata.basics.ReferenceData;
	using MarketDataId = com.opengamma.strata.data.MarketDataId;
	using MarketDataBox = com.opengamma.strata.data.scenario.MarketDataBox;

	/// <summary>
	/// A market data filter that matches a specific identifier type.
	/// </summary>
	/// @param <T>  the type of the market data handled by the filter </param>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(style = "light", constructorScope = "package") final class IdTypeFilter<T> implements MarketDataFilter<T, com.opengamma.strata.data.MarketDataId<T>>, org.joda.beans.ImmutableBean
	internal sealed class IdTypeFilter<T> : MarketDataFilter<T, MarketDataId<T>>, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final Class type;
		private readonly Type type;

	  //-------------------------------------------------------------------------
	  public Type MarketDataIdType
	  {
		  get
		  {
			return type;
		  }
	  }

	  public bool matches(MarketDataId<T> marketDataId, MarketDataBox<T> marketData, ReferenceData refData)
	  {
		return true;
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code IdTypeFilter}.
	  /// </summary>
	  private static readonly MetaBean META_BEAN = LightMetaBean.of(typeof(IdTypeFilter), MethodHandles.lookup(), new string[] {"type"}, new object[0]);

	  /// <summary>
	  /// The meta-bean for {@code IdTypeFilter}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static MetaBean meta()
	  {
		return META_BEAN;
	  }

	  static IdTypeFilter()
	  {
		MetaBean.register(META_BEAN);
	  }

	  /// <summary>
	  /// Creates an instance. </summary>
	  /// <param name="type">  the value of the property, not null </param>
	  internal IdTypeFilter(Type type)
	  {
		JodaBeanUtils.notNull(type, "type");
		this.type = type;
	  }

//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @Override @SuppressWarnings("unchecked") public org.joda.beans.TypedMetaBean<IdTypeFilter<T>> metaBean()
	  public override TypedMetaBean<IdTypeFilter<T>> metaBean()
	  {
		return (TypedMetaBean<IdTypeFilter<T>>) META_BEAN;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the type that is matched by this filter. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public Type Type
	  {
		  get
		  {
			return type;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: IdTypeFilter<?> other = (IdTypeFilter<?>) obj;
		  IdTypeFilter<object> other = (IdTypeFilter<object>) obj;
		  return JodaBeanUtils.equal(type, other.type);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(type);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(64);
		buf.Append("IdTypeFilter{");
		buf.Append("type").Append('=').Append(JodaBeanUtils.ToString(type));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}