using System;
using System.Text;

/*
 * Copyright (C) 2018 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.product.bond
{

	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using TypedMetaBean = org.joda.beans.TypedMetaBean;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using LightMetaBean = org.joda.beans.impl.light.LightMetaBean;

	using ArgChecker = com.opengamma.strata.collect.ArgChecker;

	/// <summary>
	/// The settlement details of a capital indexed bond trade.
	/// <para>
	/// When a trade in a capital indexed bond occurs there is an agreed settlement process.
	/// This class captures details of that process for the purpose of pricing.
	/// </para>
	/// <para>
	/// Once the trade has settled, end of day processing typically aggregates the trades into positions.
	/// As a position combines multiple trades at different prices, the information in this class does not apply.
	/// 
	/// <h4>Price</h4>
	/// Strata uses <i>decimal prices</i> for bonds in the trade model, pricers and market data.
	/// For example, a price of 99.32% is represented in Strata by 0.9932.
	/// </para>
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(style = "light") public final class ResolvedCapitalIndexedBondSettlement implements org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class ResolvedCapitalIndexedBondSettlement : ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final java.time.LocalDate settlementDate;
		private readonly LocalDate settlementDate;
	  /// <summary>
	  /// The <i>clean</i> price at which the bond was traded.
	  /// <para>
	  /// The "clean" price excludes any accrued interest.
	  /// </para>
	  /// <para>
	  /// Strata uses <i>decimal prices</i> for bonds in the trade model, pricers and market data.
	  /// For example, a price of 99.32% is represented in Strata by 0.9932.
	  /// </para>
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "ArgChecker.notNegative") private final double price;
	  private readonly double price;
	  /// <summary>
	  /// The payment of the settlement.
	  /// <para>
	  /// The payment sign should be compatible with the product notional and trade quantity, 
	  /// thus the payment is negative for positive quantity and positive for negative quantity.
	  /// </para>
	  /// <para>
	  /// This is effectively a fixed amount payment once the inflation rate is fixed.
	  /// </para>
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final BondPaymentPeriod payment;
	  private readonly BondPaymentPeriod payment;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Obtains an instance from the settlement date, price and amount.
	  /// </summary>
	  /// <param name="settlementDate">  the settlement date </param>
	  /// <param name="price">  the price at which the trade was agreed </param>
	  /// <param name="amount">  the amount of the settlement </param>
	  /// <returns> the settlement information </returns>
	  public static ResolvedCapitalIndexedBondSettlement of(LocalDate settlementDate, double price, BondPaymentPeriod amount)
	  {
		return new ResolvedCapitalIndexedBondSettlement(settlementDate, price, amount);
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code ResolvedCapitalIndexedBondSettlement}.
	  /// </summary>
	  private static readonly TypedMetaBean<ResolvedCapitalIndexedBondSettlement> META_BEAN = LightMetaBean.of(typeof(ResolvedCapitalIndexedBondSettlement), MethodHandles.lookup(), new string[] {"settlementDate", "price", "payment"}, new object[0]);

	  /// <summary>
	  /// The meta-bean for {@code ResolvedCapitalIndexedBondSettlement}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static TypedMetaBean<ResolvedCapitalIndexedBondSettlement> meta()
	  {
		return META_BEAN;
	  }

	  static ResolvedCapitalIndexedBondSettlement()
	  {
		MetaBean.register(META_BEAN);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private ResolvedCapitalIndexedBondSettlement(LocalDate settlementDate, double price, BondPaymentPeriod payment)
	  {
		JodaBeanUtils.notNull(settlementDate, "settlementDate");
		ArgChecker.notNegative(price, "price");
		JodaBeanUtils.notNull(payment, "payment");
		this.settlementDate = settlementDate;
		this.price = price;
		this.payment = payment;
	  }

	  public override TypedMetaBean<ResolvedCapitalIndexedBondSettlement> metaBean()
	  {
		return META_BEAN;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the settlement date. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public LocalDate SettlementDate
	  {
		  get
		  {
			return settlementDate;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the <i>clean</i> price at which the bond was traded.
	  /// <para>
	  /// The "clean" price excludes any accrued interest.
	  /// </para>
	  /// <para>
	  /// Strata uses <i>decimal prices</i> for bonds in the trade model, pricers and market data.
	  /// For example, a price of 99.32% is represented in Strata by 0.9932.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property </returns>
	  public double Price
	  {
		  get
		  {
			return price;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the payment of the settlement.
	  /// <para>
	  /// The payment sign should be compatible with the product notional and trade quantity,
	  /// thus the payment is negative for positive quantity and positive for negative quantity.
	  /// </para>
	  /// <para>
	  /// This is effectively a fixed amount payment once the inflation rate is fixed.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property, not null </returns>
	  public BondPaymentPeriod Payment
	  {
		  get
		  {
			return payment;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  ResolvedCapitalIndexedBondSettlement other = (ResolvedCapitalIndexedBondSettlement) obj;
		  return JodaBeanUtils.equal(settlementDate, other.settlementDate) && JodaBeanUtils.equal(price, other.price) && JodaBeanUtils.equal(payment, other.payment);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(settlementDate);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(price);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(payment);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(128);
		buf.Append("ResolvedCapitalIndexedBondSettlement{");
		buf.Append("settlementDate").Append('=').Append(settlementDate).Append(',').Append(' ');
		buf.Append("price").Append('=').Append(price).Append(',').Append(' ');
		buf.Append("payment").Append('=').Append(JodaBeanUtils.ToString(payment));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}