using System;

/*
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.math.impl.integration
{

	/// <summary>
	/// Gauss-Laguerre quadrature approximates the value of integrals of the form
	/// $$
	/// \begin{align*}
	/// \int_{0}^{\infty} e^{-x}f(x) dx
	/// \end{align*}
	/// $$
	/// The weights and abscissas are generated by <seealso cref="GaussLaguerreWeightAndAbscissaFunction"/>.
	/// <para>
	/// The function to integrate is scaled in such a way as to allow any values for
	/// the limits of integration. At present, this integrator can only be used for
	/// the limits $[0, \infty]$.
	/// </para>
	/// </summary>
	public class GaussLaguerreQuadratureIntegrator1D : GaussianQuadratureIntegrator1D
	{

	  private static readonly double?[] LIMITS = new double?[] {0.0, double.PositiveInfinity};

	  /// <summary>
	  /// Creates an instance. </summary>
	  /// <param name="n">  the value </param>
	  public GaussLaguerreQuadratureIntegrator1D(int n) : base(n, new GaussLaguerreWeightAndAbscissaFunction())
	  {
	  }

	  /// <summary>
	  /// Creates an instance.
	  /// </summary>
	  /// <param name="n">  the value </param>
	  /// <param name="alpha">  the alpha </param>
	  public GaussLaguerreQuadratureIntegrator1D(int n, double alpha) : base(n, new GaussLaguerreWeightAndAbscissaFunction(alpha))
	  {
	  }

	  public override double?[] Limits
	  {
		  get
		  {
			return LIMITS;
		  }
	  }

	  /// <summary>
	  /// {@inheritDoc}
	  /// The function $f(x)$ that is to be integrated is transformed into a form
	  /// suitable for this quadrature method using:
	  /// $$
	  /// \begin{align*}
	  /// \int_{0}^{\infty} f(x) dx
	  /// &= \int_{0}^{\infty} f(x) e^x e^{-x} dx\\
	  /// &= \int_{0}^{\infty} g(x) e^{-x} dx
	  /// \end{align*} 
	  /// $$ </summary>
	  /// <exception cref="UnsupportedOperationException"> If the lower limit is not $-\infty$ or the upper limit is not $\infty$ </exception>
	  public override System.Func<double, double> getIntegralFunction(System.Func<double, double> function, double? lower, double? upper)
	  {
		if (lower.Equals(LIMITS[0]) && upper.Equals(LIMITS[1]))
		{
		  return (double? x) =>
		  {
	  return function(x) * Math.Exp(x);
		  };
		}
		throw new System.NotSupportedException("Limits for Gauss-Laguerre integration are 0 and +infinity");
	  }

	}

}