using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.basics.index
{

	using Bean = org.joda.beans.Bean;
	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaProperty = org.joda.beans.impl.direct.DirectMetaProperty;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	using Currency = com.opengamma.strata.basics.currency.Currency;

	/// <summary>
	/// Information about a single observation of a Price index.
	/// <para>
	/// Observing a Price index requires knowledge of the index and fixing date.
	/// </para>
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") public final class PriceIndexObservation implements IndexObservation, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class PriceIndexObservation : IndexObservation, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull", overrideGet = true) private final PriceIndex index;
		private readonly PriceIndex index;
	  /// <summary>
	  /// The fixing month.
	  /// <para>
	  /// The index will be observed for this month.
	  /// </para>
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final java.time.YearMonth fixingMonth;
	  private readonly YearMonth fixingMonth;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Creates an instance from an index and fixing date.
	  /// <para>
	  /// The reference data is used to find the maturity date from the fixing date.
	  /// 
	  /// </para>
	  /// </summary>
	  /// <param name="index">  the index </param>
	  /// <param name="fixingMonth">  the fixing month </param>
	  /// <returns> the rate observation </returns>
	  public static PriceIndexObservation of(PriceIndex index, YearMonth fixingMonth)
	  {
		return new PriceIndexObservation(index, fixingMonth);
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the currency of the Ibor index.
	  /// </summary>
	  /// <returns> the currency of the index </returns>
	  public Currency Currency
	  {
		  get
		  {
			return index.Currency;
		  }
	  }

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Compares this observation to another based on the index and fixing date.
	  /// <para>
	  /// The maturity date is ignored.
	  /// 
	  /// </para>
	  /// </summary>
	  /// <param name="obj">  the other observation </param>
	  /// <returns> true if equal </returns>
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  PriceIndexObservation other = (PriceIndexObservation) obj;
		  return index.Equals(other.index) && fixingMonth.Equals(other.fixingMonth);
		}
		return false;
	  }

	  /// <summary>
	  /// Returns a hash code based on the index and fixing date.
	  /// <para>
	  /// The maturity date is ignored.
	  /// 
	  /// </para>
	  /// </summary>
	  /// <returns> the hash code </returns>
	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + index.GetHashCode();
		return hash * 31 + fixingMonth.GetHashCode();
	  }

	  public override string ToString()
	  {
		return (new StringBuilder(64)).Append("PriceIndexObservation[").Append(index).Append(" on ").Append(fixingMonth).Append(']').ToString();
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code PriceIndexObservation}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static PriceIndexObservation.Meta meta()
	  {
		return PriceIndexObservation.Meta.INSTANCE;
	  }

	  static PriceIndexObservation()
	  {
		MetaBean.register(PriceIndexObservation.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private PriceIndexObservation(PriceIndex index, YearMonth fixingMonth)
	  {
		JodaBeanUtils.notNull(index, "index");
		JodaBeanUtils.notNull(fixingMonth, "fixingMonth");
		this.index = index;
		this.fixingMonth = fixingMonth;
	  }

	  public override PriceIndexObservation.Meta metaBean()
	  {
		return PriceIndexObservation.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the FX index.
	  /// <para>
	  /// The rate will be queried from this index.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property, not null </returns>
	  public PriceIndex Index
	  {
		  get
		  {
			return index;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the fixing month.
	  /// <para>
	  /// The index will be observed for this month.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property, not null </returns>
	  public YearMonth FixingMonth
	  {
		  get
		  {
			return fixingMonth;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code PriceIndexObservation}.
	  /// </summary>
	  public sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  index_Renamed = DirectMetaProperty.ofImmutable(this, "index", typeof(PriceIndexObservation), typeof(PriceIndex));
			  fixingMonth_Renamed = DirectMetaProperty.ofImmutable(this, "fixingMonth", typeof(PriceIndexObservation), typeof(YearMonth));
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null, "index", "fixingMonth");
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-property for the {@code index} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<PriceIndex> index_Renamed;
		/// <summary>
		/// The meta-property for the {@code fixingMonth} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<YearMonth> fixingMonth_Renamed;
		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null, "index", "fixingMonth");
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override protected org.joda.beans.MetaProperty<?> metaPropertyGet(String propertyName)
		protected internal override MetaProperty<object> metaPropertyGet(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 100346066: // index
			  return index_Renamed;
			case 265281235: // fixingMonth
			  return fixingMonth_Renamed;
		  }
		  return base.metaPropertyGet(propertyName);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends PriceIndexObservation> builder()
		public override BeanBuilder<PriceIndexObservation> builder()
		{
		  return new PriceIndexObservation.Builder();
		}

		public override Type beanType()
		{
		  return typeof(PriceIndexObservation);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// The meta-property for the {@code index} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<PriceIndex> index()
		{
		  return index_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code fixingMonth} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<YearMonth> fixingMonth()
		{
		  return fixingMonth_Renamed;
		}

		//-----------------------------------------------------------------------
		protected internal override object propertyGet(Bean bean, string propertyName, bool quiet)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 100346066: // index
			  return ((PriceIndexObservation) bean).Index;
			case 265281235: // fixingMonth
			  return ((PriceIndexObservation) bean).FixingMonth;
		  }
		  return base.propertyGet(bean, propertyName, quiet);
		}

		protected internal override void propertySet(Bean bean, string propertyName, object newValue, bool quiet)
		{
		  metaProperty(propertyName);
		  if (quiet)
		  {
			return;
		  }
		  throw new System.NotSupportedException("Property cannot be written: " + propertyName);
		}

	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code PriceIndexObservation}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<PriceIndexObservation>
	  {

		internal PriceIndex index;
		internal YearMonth fixingMonth;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 100346066: // index
			  return index;
			case 265281235: // fixingMonth
			  return fixingMonth;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		}

		public override Builder set(string propertyName, object newValue)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 100346066: // index
			  this.index = (PriceIndex) newValue;
			  break;
			case 265281235: // fixingMonth
			  this.fixingMonth = (YearMonth) newValue;
			  break;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		  return this;
		}

		public override PriceIndexObservation build()
		{
		  return new PriceIndexObservation(index, fixingMonth);
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  StringBuilder buf = new StringBuilder(96);
		  buf.Append("PriceIndexObservation.Builder{");
		  buf.Append("index").Append('=').Append(JodaBeanUtils.ToString(index)).Append(',').Append(' ');
		  buf.Append("fixingMonth").Append('=').Append(JodaBeanUtils.ToString(fixingMonth));
		  buf.Append('}');
		  return buf.ToString();
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}