using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.product.swaption
{

	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	using SettlementType = com.opengamma.strata.product.common.SettlementType;

	/// <summary>
	/// Defines the settlement type and settlement method of swaptions.
	/// <para>
	/// The settlement type is <seealso cref="SettlementType#PHYSICAL"/>. This means that the two
	/// parties enter into the actual interest rate swap at the expiry date of the option.
	/// </para>
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") public final class PhysicalSwaptionSettlement implements SwaptionSettlement, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class PhysicalSwaptionSettlement : SwaptionSettlement, ImmutableBean
	{

	  /// <summary>
	  /// Default instance.
	  /// </summary>
	  public static readonly PhysicalSwaptionSettlement DEFAULT = new PhysicalSwaptionSettlement();

	  public SettlementType SettlementType
	  {
		  get
		  {
			return SettlementType.PHYSICAL;
		  }
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code PhysicalSwaptionSettlement}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static PhysicalSwaptionSettlement.Meta meta()
	  {
		return PhysicalSwaptionSettlement.Meta.INSTANCE;
	  }

	  static PhysicalSwaptionSettlement()
	  {
		MetaBean.register(PhysicalSwaptionSettlement.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private PhysicalSwaptionSettlement()
	  {
	  }

	  public override PhysicalSwaptionSettlement.Meta metaBean()
	  {
		return PhysicalSwaptionSettlement.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  return true;
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(32);
		buf.Append("PhysicalSwaptionSettlement{");
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code PhysicalSwaptionSettlement}.
	  /// </summary>
	  public sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null);
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null);
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends PhysicalSwaptionSettlement> builder()
		public override BeanBuilder<PhysicalSwaptionSettlement> builder()
		{
		  return new PhysicalSwaptionSettlement.Builder();
		}

		public override Type beanType()
		{
		  return typeof(PhysicalSwaptionSettlement);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code PhysicalSwaptionSettlement}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<PhysicalSwaptionSettlement>
	  {

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  throw new NoSuchElementException("Unknown property: " + propertyName);
		}

		public override Builder set(string propertyName, object newValue)
		{
		  throw new NoSuchElementException("Unknown property: " + propertyName);
		}

		public override PhysicalSwaptionSettlement build()
		{
		  return new PhysicalSwaptionSettlement();
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  return "PhysicalSwaptionSettlement.Builder{}";
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}