using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.market.param
{

	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	/// <summary>
	/// Empty parameter metadata, used when there is no applicable metadata.
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") final class EmptyParameterMetadata implements ParameterMetadata, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	internal sealed class EmptyParameterMetadata : ParameterMetadata, ImmutableBean
	{

	  /// <summary>
	  /// The singleton instance.
	  /// </summary>
	  private static readonly EmptyParameterMetadata INSTANCE = new EmptyParameterMetadata();

	  /// <summary>
	  /// The description and identifier.
	  /// </summary>
	  private const string EMPTY = "";

	  /// <summary>
	  /// Obtains the empty instance.
	  /// </summary>
	  /// <returns> the metadata </returns>
	  internal static EmptyParameterMetadata empty()
	  {
		return INSTANCE;
	  }

	  //-------------------------------------------------------------------------
	  public string Label
	  {
		  get
		  {
			return EMPTY;
		  }
	  }

	  /// <summary>
	  /// Returns an empty string.
	  /// </summary>
	  /// <returns> a simple identifier </returns>
	  public string Identifier
	  {
		  get
		  {
			return EMPTY;
		  }
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code EmptyParameterMetadata}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static EmptyParameterMetadata.Meta meta()
	  {
		return EmptyParameterMetadata.Meta.INSTANCE;
	  }

	  static EmptyParameterMetadata()
	  {
		MetaBean.register(EmptyParameterMetadata.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private EmptyParameterMetadata()
	  {
	  }

	  public override EmptyParameterMetadata.Meta metaBean()
	  {
		return EmptyParameterMetadata.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  return true;
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(32);
		buf.Append("EmptyParameterMetadata{");
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code EmptyParameterMetadata}.
	  /// </summary>
	  internal sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null);
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null);
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends EmptyParameterMetadata> builder()
		public override BeanBuilder<EmptyParameterMetadata> builder()
		{
		  return new EmptyParameterMetadata.Builder();
		}

		public override Type beanType()
		{
		  return typeof(EmptyParameterMetadata);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code EmptyParameterMetadata}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<EmptyParameterMetadata>
	  {

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  throw new NoSuchElementException("Unknown property: " + propertyName);
		}

		public override Builder set(string propertyName, object newValue)
		{
		  throw new NoSuchElementException("Unknown property: " + propertyName);
		}

		public override EmptyParameterMetadata build()
		{
		  return new EmptyParameterMetadata();
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  return "EmptyParameterMetadata.Builder{}";
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}