using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2017 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.market.param
{

	using Bean = org.joda.beans.Bean;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using DirectFieldsBeanBuilder = org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaProperty = org.joda.beans.impl.direct.DirectMetaProperty;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;

	using ResolvedTrade = com.opengamma.strata.product.ResolvedTrade;

	/// <summary>
	/// Parameter metadata based on a resolved trade and label.
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition public final class ResolvedTradeParameterMetadata implements ParameterMetadata, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class ResolvedTradeParameterMetadata : ParameterMetadata, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final com.opengamma.strata.product.ResolvedTrade trade;
		private readonly ResolvedTrade trade;
	  /// <summary>
	  /// The label that describes the parameter.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notEmpty", overrideGet = true) private final String label;
	  private readonly string label;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Obtains an instance specifying the trade and label.
	  /// </summary>
	  /// <param name="trade">  the resolved trade </param>
	  /// <param name="label">  the label </param>
	  /// <returns> the instance </returns>
	  public static ResolvedTradeParameterMetadata of(ResolvedTrade trade, string label)
	  {
		return new ResolvedTradeParameterMetadata(trade, label);
	  }

	  //-------------------------------------------------------------------------
	  public string Identifier
	  {
		  get
		  {
			return Label;
		  }
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code ResolvedTradeParameterMetadata}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static ResolvedTradeParameterMetadata.Meta meta()
	  {
		return ResolvedTradeParameterMetadata.Meta.INSTANCE;
	  }

	  static ResolvedTradeParameterMetadata()
	  {
		MetaBean.register(ResolvedTradeParameterMetadata.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  /// <summary>
	  /// Returns a builder used to create an instance of the bean. </summary>
	  /// <returns> the builder, not null </returns>
	  public static ResolvedTradeParameterMetadata.Builder builder()
	  {
		return new ResolvedTradeParameterMetadata.Builder();
	  }

	  private ResolvedTradeParameterMetadata(ResolvedTrade trade, string label)
	  {
		JodaBeanUtils.notNull(trade, "trade");
		JodaBeanUtils.notEmpty(label, "label");
		this.trade = trade;
		this.label = label;
	  }

	  public override ResolvedTradeParameterMetadata.Meta metaBean()
	  {
		return ResolvedTradeParameterMetadata.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the trade that describes the parameter. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public ResolvedTrade Trade
	  {
		  get
		  {
			return trade;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the label that describes the parameter. </summary>
	  /// <returns> the value of the property, not empty </returns>
	  public string Label
	  {
		  get
		  {
			return label;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Returns a builder that allows this bean to be mutated. </summary>
	  /// <returns> the mutable builder, not null </returns>
	  public Builder toBuilder()
	  {
		return new Builder(this);
	  }

	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  ResolvedTradeParameterMetadata other = (ResolvedTradeParameterMetadata) obj;
		  return JodaBeanUtils.equal(trade, other.trade) && JodaBeanUtils.equal(label, other.label);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(trade);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(label);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(96);
		buf.Append("ResolvedTradeParameterMetadata{");
		buf.Append("trade").Append('=').Append(trade).Append(',').Append(' ');
		buf.Append("label").Append('=').Append(JodaBeanUtils.ToString(label));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code ResolvedTradeParameterMetadata}.
	  /// </summary>
	  public sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  trade_Renamed = DirectMetaProperty.ofImmutable(this, "trade", typeof(ResolvedTradeParameterMetadata), typeof(ResolvedTrade));
			  label_Renamed = DirectMetaProperty.ofImmutable(this, "label", typeof(ResolvedTradeParameterMetadata), typeof(string));
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null, "trade", "label");
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-property for the {@code trade} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<ResolvedTrade> trade_Renamed;
		/// <summary>
		/// The meta-property for the {@code label} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<string> label_Renamed;
		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null, "trade", "label");
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override protected org.joda.beans.MetaProperty<?> metaPropertyGet(String propertyName)
		protected internal override MetaProperty<object> metaPropertyGet(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 110621028: // trade
			  return trade_Renamed;
			case 102727412: // label
			  return label_Renamed;
		  }
		  return base.metaPropertyGet(propertyName);
		}

		public override ResolvedTradeParameterMetadata.Builder builder()
		{
		  return new ResolvedTradeParameterMetadata.Builder();
		}

		public override Type beanType()
		{
		  return typeof(ResolvedTradeParameterMetadata);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// The meta-property for the {@code trade} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<ResolvedTrade> trade()
		{
		  return trade_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code label} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<string> label()
		{
		  return label_Renamed;
		}

		//-----------------------------------------------------------------------
		protected internal override object propertyGet(Bean bean, string propertyName, bool quiet)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 110621028: // trade
			  return ((ResolvedTradeParameterMetadata) bean).Trade;
			case 102727412: // label
			  return ((ResolvedTradeParameterMetadata) bean).Label;
		  }
		  return base.propertyGet(bean, propertyName, quiet);
		}

		protected internal override void propertySet(Bean bean, string propertyName, object newValue, bool quiet)
		{
		  metaProperty(propertyName);
		  if (quiet)
		  {
			return;
		  }
		  throw new System.NotSupportedException("Property cannot be written: " + propertyName);
		}

	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code ResolvedTradeParameterMetadata}.
	  /// </summary>
	  public sealed class Builder : DirectFieldsBeanBuilder<ResolvedTradeParameterMetadata>
	  {

//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal ResolvedTrade trade_Renamed;
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal string label_Renamed;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		/// <summary>
		/// Restricted copy constructor. </summary>
		/// <param name="beanToCopy">  the bean to copy from, not null </param>
		internal Builder(ResolvedTradeParameterMetadata beanToCopy)
		{
		  this.trade_Renamed = beanToCopy.Trade;
		  this.label_Renamed = beanToCopy.Label;
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 110621028: // trade
			  return trade_Renamed;
			case 102727412: // label
			  return label_Renamed;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		}

		public override Builder set(string propertyName, object newValue)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 110621028: // trade
			  this.trade_Renamed = (ResolvedTrade) newValue;
			  break;
			case 102727412: // label
			  this.label_Renamed = (string) newValue;
			  break;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		  return this;
		}

		public override Builder set<T1>(MetaProperty<T1> property, object value)
		{
		  base.set(property, value);
		  return this;
		}

		public override ResolvedTradeParameterMetadata build()
		{
		  return new ResolvedTradeParameterMetadata(trade_Renamed, label_Renamed);
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// Sets the trade that describes the parameter. </summary>
		/// <param name="trade">  the new value, not null </param>
		/// <returns> this, for chaining, not null </returns>
		public Builder trade(ResolvedTrade trade)
		{
		  JodaBeanUtils.notNull(trade, "trade");
		  this.trade_Renamed = trade;
		  return this;
		}

		/// <summary>
		/// Sets the label that describes the parameter. </summary>
		/// <param name="label">  the new value, not empty </param>
		/// <returns> this, for chaining, not null </returns>
		public Builder label(string label)
		{
		  JodaBeanUtils.notEmpty(label, "label");
		  this.label_Renamed = label;
		  return this;
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  StringBuilder buf = new StringBuilder(96);
		  buf.Append("ResolvedTradeParameterMetadata.Builder{");
		  buf.Append("trade").Append('=').Append(JodaBeanUtils.ToString(trade_Renamed)).Append(',').Append(' ');
		  buf.Append("label").Append('=').Append(JodaBeanUtils.ToString(label_Renamed));
		  buf.Append('}');
		  return buf.ToString();
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}