using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.market.param
{

	using Bean = org.joda.beans.Bean;
	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using ImmutablePreBuild = org.joda.beans.gen.ImmutablePreBuild;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaProperty = org.joda.beans.impl.direct.DirectMetaProperty;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	using Tenor = com.opengamma.strata.basics.date.Tenor;
	using ArgChecker = com.opengamma.strata.collect.ArgChecker;

	/// <summary>
	/// Parameter metadata based on a date and tenor.
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") public final class TenorDateParameterMetadata implements DatedParameterMetadata, TenoredParameterMetadata, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class TenorDateParameterMetadata : DatedParameterMetadata, TenoredParameterMetadata, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull", overrideGet = true) private final java.time.LocalDate date;
		private readonly LocalDate date;
	  /// <summary>
	  /// The tenor associated with the parameter.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull", overrideGet = true) private final com.opengamma.strata.basics.date.Tenor tenor;
	  private readonly Tenor tenor;
	  /// <summary>
	  /// The label that describes the parameter, defaulted to the tenor.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notEmpty", overrideGet = true) private final String label;
	  private readonly string label;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Obtains an instance using the tenor.
	  /// </summary>
	  /// <param name="date">  the date associated with the parameter </param>
	  /// <param name="tenor">  the tenor associated with the parameter </param>
	  /// <returns> the parameter metadata based on the tenor </returns>
	  public static TenorDateParameterMetadata of(LocalDate date, Tenor tenor)
	  {
		ArgChecker.notNull(date, "date");
		ArgChecker.notNull(tenor, "tenor");
		return new TenorDateParameterMetadata(date, tenor, tenor.ToString());
	  }

	  /// <summary>
	  /// Obtains an instance using the tenor, specifying the label.
	  /// </summary>
	  /// <param name="date">  the date associated with the parameter </param>
	  /// <param name="tenor">  the tenor associated with the parameter </param>
	  /// <param name="label">  the label to use </param>
	  /// <returns> the parameter metadata based on the tenor </returns>
	  public static TenorDateParameterMetadata of(LocalDate date, Tenor tenor, string label)
	  {
		return new TenorDateParameterMetadata(date, tenor, label);
	  }

//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @ImmutablePreBuild private static void preBuild(Builder builder)
	  private static void preBuild(Builder builder)
	  {
		if (string.ReferenceEquals(builder.label, null) && builder.tenor != null)
		{
		  builder.label = builder.tenor.ToString();
		}
	  }

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Gets the identifier, which is the tenor.
	  /// </summary>
	  /// <returns> the tenor </returns>
	  public Tenor Identifier
	  {
		  get
		  {
			return tenor;
		  }
	  }

	  public TenorDateParameterMetadata withTenor(Tenor tenor)
	  {
		if (this.tenor.Equals(tenor))
		{
		  return this;
		}
		if (label.Equals(this.tenor.ToString()))
		{
		  return TenorDateParameterMetadata.of(date, tenor);
		}
		else
		{
		  return TenorDateParameterMetadata.of(date, tenor, label);
		}
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code TenorDateParameterMetadata}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static TenorDateParameterMetadata.Meta meta()
	  {
		return TenorDateParameterMetadata.Meta.INSTANCE;
	  }

	  static TenorDateParameterMetadata()
	  {
		MetaBean.register(TenorDateParameterMetadata.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private TenorDateParameterMetadata(LocalDate date, Tenor tenor, string label)
	  {
		JodaBeanUtils.notNull(date, "date");
		JodaBeanUtils.notNull(tenor, "tenor");
		JodaBeanUtils.notEmpty(label, "label");
		this.date = date;
		this.tenor = tenor;
		this.label = label;
	  }

	  public override TenorDateParameterMetadata.Meta metaBean()
	  {
		return TenorDateParameterMetadata.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the date associated with the parameter.
	  /// <para>
	  /// This is the date that is most closely associated with the parameter.
	  /// The actual parameter is typically a year fraction based on a day count.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property, not null </returns>
	  public LocalDate Date
	  {
		  get
		  {
			return date;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the tenor associated with the parameter. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public Tenor Tenor
	  {
		  get
		  {
			return tenor;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the label that describes the parameter, defaulted to the tenor. </summary>
	  /// <returns> the value of the property, not empty </returns>
	  public string Label
	  {
		  get
		  {
			return label;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  TenorDateParameterMetadata other = (TenorDateParameterMetadata) obj;
		  return JodaBeanUtils.equal(date, other.date) && JodaBeanUtils.equal(tenor, other.tenor) && JodaBeanUtils.equal(label, other.label);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(date);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(tenor);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(label);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(128);
		buf.Append("TenorDateParameterMetadata{");
		buf.Append("date").Append('=').Append(date).Append(',').Append(' ');
		buf.Append("tenor").Append('=').Append(tenor).Append(',').Append(' ');
		buf.Append("label").Append('=').Append(JodaBeanUtils.ToString(label));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code TenorDateParameterMetadata}.
	  /// </summary>
	  public sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  date_Renamed = DirectMetaProperty.ofImmutable(this, "date", typeof(TenorDateParameterMetadata), typeof(LocalDate));
			  tenor_Renamed = DirectMetaProperty.ofImmutable(this, "tenor", typeof(TenorDateParameterMetadata), typeof(Tenor));
			  label_Renamed = DirectMetaProperty.ofImmutable(this, "label", typeof(TenorDateParameterMetadata), typeof(string));
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null, "date", "tenor", "label");
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-property for the {@code date} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<LocalDate> date_Renamed;
		/// <summary>
		/// The meta-property for the {@code tenor} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<Tenor> tenor_Renamed;
		/// <summary>
		/// The meta-property for the {@code label} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<string> label_Renamed;
		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null, "date", "tenor", "label");
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override protected org.joda.beans.MetaProperty<?> metaPropertyGet(String propertyName)
		protected internal override MetaProperty<object> metaPropertyGet(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 3076014: // date
			  return date_Renamed;
			case 110246592: // tenor
			  return tenor_Renamed;
			case 102727412: // label
			  return label_Renamed;
		  }
		  return base.metaPropertyGet(propertyName);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends TenorDateParameterMetadata> builder()
		public override BeanBuilder<TenorDateParameterMetadata> builder()
		{
		  return new TenorDateParameterMetadata.Builder();
		}

		public override Type beanType()
		{
		  return typeof(TenorDateParameterMetadata);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// The meta-property for the {@code date} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<LocalDate> date()
		{
		  return date_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code tenor} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<Tenor> tenor()
		{
		  return tenor_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code label} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<string> label()
		{
		  return label_Renamed;
		}

		//-----------------------------------------------------------------------
		protected internal override object propertyGet(Bean bean, string propertyName, bool quiet)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 3076014: // date
			  return ((TenorDateParameterMetadata) bean).Date;
			case 110246592: // tenor
			  return ((TenorDateParameterMetadata) bean).Tenor;
			case 102727412: // label
			  return ((TenorDateParameterMetadata) bean).Label;
		  }
		  return base.propertyGet(bean, propertyName, quiet);
		}

		protected internal override void propertySet(Bean bean, string propertyName, object newValue, bool quiet)
		{
		  metaProperty(propertyName);
		  if (quiet)
		  {
			return;
		  }
		  throw new System.NotSupportedException("Property cannot be written: " + propertyName);
		}

	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code TenorDateParameterMetadata}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<TenorDateParameterMetadata>
	  {

		internal LocalDate date;
		internal Tenor tenor;
		internal string label;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 3076014: // date
			  return date;
			case 110246592: // tenor
			  return tenor;
			case 102727412: // label
			  return label;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		}

		public override Builder set(string propertyName, object newValue)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 3076014: // date
			  this.date = (LocalDate) newValue;
			  break;
			case 110246592: // tenor
			  this.tenor = (Tenor) newValue;
			  break;
			case 102727412: // label
			  this.label = (string) newValue;
			  break;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		  return this;
		}

		public override TenorDateParameterMetadata build()
		{
		  preBuild(this);
		  return new TenorDateParameterMetadata(date, tenor, label);
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  StringBuilder buf = new StringBuilder(128);
		  buf.Append("TenorDateParameterMetadata.Builder{");
		  buf.Append("date").Append('=').Append(JodaBeanUtils.ToString(date)).Append(',').Append(' ');
		  buf.Append("tenor").Append('=').Append(JodaBeanUtils.ToString(tenor)).Append(',').Append(' ');
		  buf.Append("label").Append('=').Append(JodaBeanUtils.ToString(label));
		  buf.Append('}');
		  return buf.ToString();
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}