using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.data.scenario
{
//JAVA TO C# CONVERTER TODO TASK: This Java 'import static' statement cannot be converted to C#:
//	import static com.opengamma.strata.collect.Guavate.toImmutableList;


	using Bean = org.joda.beans.Bean;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using DirectFieldsBeanBuilder = org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaProperty = org.joda.beans.impl.direct.DirectMetaProperty;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;

	using ArgChecker = com.opengamma.strata.collect.ArgChecker;
	using ObjIntFunction = com.opengamma.strata.collect.function.ObjIntFunction;

	/// <summary>
	/// A market data box containing a single value which is used in all scenarios.
	/// <para>
	/// A market data box containing a single value can therefore be used with any number of scenarios.
	/// 
	/// </para>
	/// </summary>
	/// @param <T>  the type of data held in the box </param>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition final class SingleMarketDataBox<T> implements org.joda.beans.ImmutableBean, MarketDataBox<T>, java.io.Serializable
	[Serializable]
	internal sealed class SingleMarketDataBox<T> : ImmutableBean, MarketDataBox<T>
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final T value;
		private readonly T value;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Obtains an instance containing a single market data value.
	  /// </summary>
	  /// @param <T> the type of the value </param>
	  /// <param name="value">  the market data value </param>
	  /// <returns> a market data box containing a single market data value </returns>
	  public static SingleMarketDataBox<T> of<T>(T value)
	  {
		return new SingleMarketDataBox<T>(value);
	  }

	  //-------------------------------------------------------------------------
	  public T SingleValue
	  {
		  get
		  {
			return value;
		  }
	  }

	  public ScenarioArray<T> ScenarioValue
	  {
		  get
		  {
			throw new System.InvalidOperationException("This box does not contain a scenario value");
		  }
	  }

	  public T getValue(int scenarioIndex)
	  {
		ArgChecker.notNegative(scenarioIndex, "scenarioIndex");
		return value;
	  }

	  public bool SingleValue
	  {
		  get
		  {
			return true;
		  }
	  }

	  public int ScenarioCount
	  {
		  get
		  {
			return -1;
		  }
	  }

	  public Type MarketDataType
	  {
		  get
		  {
			return value.GetType();
		  }
	  }

	  //-------------------------------------------------------------------------
	  public MarketDataBox<R> map<R>(System.Func<T, R> fn)
	  {
		return MarketDataBox.ofSingleValue(fn(value));
	  }

	  public MarketDataBox<R> mapWithIndex<R>(int scenarioCount, ObjIntFunction<T, R> fn)
	  {
		IList<R> perturbedValues = IntStream.range(0, scenarioCount).mapToObj(idx => fn.apply(value, idx)).collect(toImmutableList());
		return MarketDataBox.ofScenarioValues(perturbedValues);
	  }

	  public MarketDataBox<R> combineWith<U, R>(MarketDataBox<U> other, System.Func<T, U, R> fn)
	  {
		return other.SingleValue ? combineWithSingle(other, fn) : combineWithMultiple(other, fn);
	  }

	  private MarketDataBox<R> combineWithMultiple<U, R>(MarketDataBox<U> other, System.Func<T, U, R> fn)
	  {
		ScenarioArray<U> otherValue = other.ScenarioValue;
		int scenarioCount = otherValue.ScenarioCount;

		IList<R> values = IntStream.range(0, scenarioCount).mapToObj(i => fn(value, other.getValue(i))).collect(toImmutableList());
		return MarketDataBox.ofScenarioValues(values);
	  }

	  private MarketDataBox<R> combineWithSingle<U, R>(MarketDataBox<U> other, System.Func<T, U, R> fn)
	  {
		U otherValue = other.SingleValue;
		return MarketDataBox.ofSingleValue(fn(value, otherValue));
	  }

	  public Stream<T> stream()
	  {
		return Stream.of(value);
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code SingleMarketDataBox}. </summary>
	  /// <returns> the meta-bean, not null </returns>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings("rawtypes") public static SingleMarketDataBox.Meta meta()
	  public static SingleMarketDataBox.Meta meta()
	  {
		return SingleMarketDataBox.Meta.INSTANCE;
	  }

	  /// <summary>
	  /// The meta-bean for {@code SingleMarketDataBox}. </summary>
	  /// @param <R>  the bean's generic type </param>
	  /// <param name="cls">  the bean's generic type </param>
	  /// <returns> the meta-bean, not null </returns>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings("unchecked") public static <R> SingleMarketDataBox.Meta<R> metaSingleMarketDataBox(Class<R> cls)
	  public static SingleMarketDataBox.Meta<R> metaSingleMarketDataBox<R>(Type<R> cls)
	  {
		return SingleMarketDataBox.Meta.INSTANCE;
	  }

	  static SingleMarketDataBox()
	  {
		MetaBean.register(SingleMarketDataBox.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  /// <summary>
	  /// Returns a builder used to create an instance of the bean. </summary>
	  /// @param <T>  the type </param>
	  /// <returns> the builder, not null </returns>
	  internal static SingleMarketDataBox.Builder<T> builder<T>()
	  {
		return new SingleMarketDataBox.Builder<T>();
	  }

	  private SingleMarketDataBox(T value)
	  {
		JodaBeanUtils.notNull(value, "value");
		this.value = value;
	  }

//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings("unchecked") @Override public SingleMarketDataBox.Meta<T> metaBean()
	  public override SingleMarketDataBox.Meta<T> metaBean()
	  {
		return SingleMarketDataBox.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the market data value used in all scenarios. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public T Value
	  {
		  get
		  {
			return value;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Returns a builder that allows this bean to be mutated. </summary>
	  /// <returns> the mutable builder, not null </returns>
	  internal Builder<T> toBuilder()
	  {
		return new Builder<T>(this);
	  }

	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: SingleMarketDataBox<?> other = (SingleMarketDataBox<?>) obj;
		  SingleMarketDataBox<object> other = (SingleMarketDataBox<object>) obj;
		  return JodaBeanUtils.equal(value, other.value);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(value);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(64);
		buf.Append("SingleMarketDataBox{");
		buf.Append("value").Append('=').Append(JodaBeanUtils.ToString(value));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code SingleMarketDataBox}. </summary>
	  /// @param <T>  the type </param>
	  internal sealed class Meta<T> : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  value_Renamed = (DirectMetaProperty) DirectMetaProperty.ofImmutable(this, "value", typeof(SingleMarketDataBox), typeof(object));
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null, "value");
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings("rawtypes") static final Meta INSTANCE = new Meta();
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-property for the {@code value} property.
		/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings({"unchecked", "rawtypes" }) private final org.joda.beans.MetaProperty<T> value = (org.joda.beans.impl.direct.DirectMetaProperty) org.joda.beans.impl.direct.DirectMetaProperty.ofImmutable(this, "value", SingleMarketDataBox.class, Object.class);
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<T> value_Renamed;
		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null, "value");
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override protected org.joda.beans.MetaProperty<?> metaPropertyGet(String propertyName)
		protected internal override MetaProperty<object> metaPropertyGet(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 111972721: // value
			  return value_Renamed;
		  }
		  return base.metaPropertyGet(propertyName);
		}

		public override SingleMarketDataBox.Builder<T> builder()
		{
		  return new SingleMarketDataBox.Builder<T>();
		}

//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings({"unchecked", "rawtypes" }) @Override public Class beanType()
		public override Type beanType()
		{
		  return (Type) typeof(SingleMarketDataBox);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// The meta-property for the {@code value} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<T> value()
		{
		  return value_Renamed;
		}

		//-----------------------------------------------------------------------
		protected internal override object propertyGet(Bean bean, string propertyName, bool quiet)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 111972721: // value
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: return ((SingleMarketDataBox<?>) bean).getValue();
			  return ((SingleMarketDataBox<object>) bean).Value;
		  }
		  return base.propertyGet(bean, propertyName, quiet);
		}

		protected internal override void propertySet(Bean bean, string propertyName, object newValue, bool quiet)
		{
		  metaProperty(propertyName);
		  if (quiet)
		  {
			return;
		  }
		  throw new System.NotSupportedException("Property cannot be written: " + propertyName);
		}

	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code SingleMarketDataBox}. </summary>
	  /// @param <T>  the type </param>
	  internal sealed class Builder<T> : DirectFieldsBeanBuilder<SingleMarketDataBox<T>>
	  {

//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal T value_Renamed;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		/// <summary>
		/// Restricted copy constructor. </summary>
		/// <param name="beanToCopy">  the bean to copy from, not null </param>
		internal Builder(SingleMarketDataBox<T> beanToCopy)
		{
		  this.value_Renamed = beanToCopy.Value;
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 111972721: // value
			  return value_Renamed;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		}

//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings("unchecked") @Override public Builder<T> set(String propertyName, Object newValue)
		public override Builder<T> set(string propertyName, object newValue)
		{
		  switch (propertyName.GetHashCode())
		  {
			case 111972721: // value
			  this.value_Renamed = (T) newValue;
			  break;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		  return this;
		}

		public override Builder<T> set<T1>(MetaProperty<T1> property, object value)
		{
		  base.set(property, value);
		  return this;
		}

		public override SingleMarketDataBox<T> build()
		{
		  return new SingleMarketDataBox<T>(value_Renamed);
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// Sets the market data value used in all scenarios. </summary>
		/// <param name="value">  the new value, not null </param>
		/// <returns> this, for chaining, not null </returns>
		public Builder<T> value(T value)
		{
		  JodaBeanUtils.notNull(value, "value");
		  this.value_Renamed = value;
		  return this;
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  StringBuilder buf = new StringBuilder(64);
		  buf.Append("SingleMarketDataBox.Builder{");
		  buf.Append("value").Append('=').Append(JodaBeanUtils.ToString(value_Renamed));
		  buf.Append('}');
		  return buf.ToString();
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}