using System;
using System.Text;

/*
 * Copyright (C) 2018 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.market.curve
{

	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using TypedMetaBean = org.joda.beans.TypedMetaBean;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using LightMetaBean = org.joda.beans.impl.light.LightMetaBean;

	using MarketDataId = com.opengamma.strata.data.MarketDataId;
	using ObservableSource = com.opengamma.strata.data.ObservableSource;

	/// <summary>
	/// An identifier used to access a curve group by name.
	/// <para>
	/// This is used when there is a need to obtain an instance of <seealso cref="LegalEntityCurveGroup"/>.
	/// </para>
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(style = "light", cacheHashCode = true) public final class LegalEntityCurveGroupId implements com.opengamma.strata.data.MarketDataId<LegalEntityCurveGroup>, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class LegalEntityCurveGroupId : MarketDataId<LegalEntityCurveGroup>, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final CurveGroupName curveGroupName;
		private readonly CurveGroupName curveGroupName;
	  /// <summary>
	  /// The source of observable market data.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final com.opengamma.strata.data.ObservableSource observableSource;
	  private readonly ObservableSource observableSource;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Obtains an instance used to obtain a curve group by name.
	  /// </summary>
	  /// <param name="groupName">  the curve group name </param>
	  /// <returns> the identifier </returns>
	  public static LegalEntityCurveGroupId of(string groupName)
	  {
		return new LegalEntityCurveGroupId(CurveGroupName.of(groupName), ObservableSource.NONE);
	  }

	  /// <summary>
	  /// Obtains an instance used to obtain a curve group by name.
	  /// </summary>
	  /// <param name="groupName">  the curve group name </param>
	  /// <returns> the identifier </returns>
	  public static LegalEntityCurveGroupId of(CurveGroupName groupName)
	  {
		return new LegalEntityCurveGroupId(groupName, ObservableSource.NONE);
	  }

	  /// <summary>
	  /// Obtains an instance used to obtain a curve group by name, specifying the source of observable market data.
	  /// </summary>
	  /// <param name="groupName">  the curve group name </param>
	  /// <param name="obsSource">  source of observable market data </param>
	  /// <returns> the identifier </returns>
	  public static LegalEntityCurveGroupId of(CurveGroupName groupName, ObservableSource obsSource)
	  {
		return new LegalEntityCurveGroupId(groupName, obsSource);
	  }

	  //-------------------------------------------------------------------------
	  public Type<LegalEntityCurveGroup> MarketDataType
	  {
		  get
		  {
			return typeof(LegalEntityCurveGroup);
		  }
	  }

	  public override string ToString()
	  {
		return (new StringBuilder(32)).Append("LegalEntityCurveGroupId:").Append(curveGroupName).Append(observableSource.Equals(ObservableSource.NONE) ? "" : "/" + observableSource).ToString();
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code LegalEntityCurveGroupId}.
	  /// </summary>
	  private static readonly TypedMetaBean<LegalEntityCurveGroupId> META_BEAN = LightMetaBean.of(typeof(LegalEntityCurveGroupId), MethodHandles.lookup(), new string[] {"curveGroupName", "observableSource"}, new object[0]);

	  /// <summary>
	  /// The meta-bean for {@code LegalEntityCurveGroupId}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static TypedMetaBean<LegalEntityCurveGroupId> meta()
	  {
		return META_BEAN;
	  }

	  static LegalEntityCurveGroupId()
	  {
		MetaBean.register(META_BEAN);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  /// <summary>
	  /// The cached hash code, using the racy single-check idiom.
	  /// </summary>
	  [NonSerialized]
	  private int cacheHashCode;

	  private LegalEntityCurveGroupId(CurveGroupName curveGroupName, ObservableSource observableSource)
	  {
		JodaBeanUtils.notNull(curveGroupName, "curveGroupName");
		JodaBeanUtils.notNull(observableSource, "observableSource");
		this.curveGroupName = curveGroupName;
		this.observableSource = observableSource;
	  }

	  public override TypedMetaBean<LegalEntityCurveGroupId> metaBean()
	  {
		return META_BEAN;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the curve group name. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public CurveGroupName CurveGroupName
	  {
		  get
		  {
			return curveGroupName;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the source of observable market data. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public ObservableSource ObservableSource
	  {
		  get
		  {
			return observableSource;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  LegalEntityCurveGroupId other = (LegalEntityCurveGroupId) obj;
		  return JodaBeanUtils.equal(curveGroupName, other.curveGroupName) && JodaBeanUtils.equal(observableSource, other.observableSource);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = cacheHashCode;
		if (hash == 0)
		{
		  hash = this.GetType().GetHashCode();
		  hash = hash * 31 + JodaBeanUtils.GetHashCode(curveGroupName);
		  hash = hash * 31 + JodaBeanUtils.GetHashCode(observableSource);
		  cacheHashCode = hash;
		}
		return hash;
	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}