using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.market.surface
{

	using Bean = org.joda.beans.Bean;
	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaProperty = org.joda.beans.impl.direct.DirectMetaProperty;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	using ParameterMetadata = com.opengamma.strata.market.param.ParameterMetadata;

	/// <summary>
	/// Simple parameter metadata containing the x and y values and type.
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") public final class SimpleSurfaceParameterMetadata implements com.opengamma.strata.market.param.ParameterMetadata, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class SimpleSurfaceParameterMetadata : ParameterMetadata, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final com.opengamma.strata.market.ValueType xValueType;
		private readonly ValueType xValueType;
	  /// <summary>
	  /// The x-value.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition private final double xValue;
	  private readonly double xValue;
	  /// <summary>
	  /// The type of the y-value.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final com.opengamma.strata.market.ValueType yValueType;
	  private readonly ValueType yValueType;
	  /// <summary>
	  /// The y-value.
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition private final double yValue;
	  private readonly double yValue;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Obtains an instance specifying information about the x-value.
	  /// </summary>
	  /// <param name="xValueType">  the x-value type </param>
	  /// <param name="xValue">  the x-value </param>
	  /// <param name="yValueType">  the x-value type </param>
	  /// <param name="yValue">  the x-value </param>
	  /// <returns> the parameter metadata based on the date and label </returns>
	  public static SimpleSurfaceParameterMetadata of(ValueType xValueType, double xValue, ValueType yValueType, double yValue)
	  {

		return new SimpleSurfaceParameterMetadata(xValueType, xValue, yValueType, yValue);
	  }

	  //-------------------------------------------------------------------------
	  public string Label
	  {
		  get
		  {
			return xValueType + "=" + xValue + ", " + yValueType + "=" + yValue;
		  }
	  }

	  public string Identifier
	  {
		  get
		  {
			return Label;
		  }
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code SimpleSurfaceParameterMetadata}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static SimpleSurfaceParameterMetadata.Meta meta()
	  {
		return SimpleSurfaceParameterMetadata.Meta.INSTANCE;
	  }

	  static SimpleSurfaceParameterMetadata()
	  {
		MetaBean.register(SimpleSurfaceParameterMetadata.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private SimpleSurfaceParameterMetadata(ValueType xValueType, double xValue, ValueType yValueType, double yValue)
	  {
		JodaBeanUtils.notNull(xValueType, "xValueType");
		JodaBeanUtils.notNull(yValueType, "yValueType");
		this.xValueType = xValueType;
		this.xValue = xValue;
		this.yValueType = yValueType;
		this.yValue = yValue;
	  }

	  public override SimpleSurfaceParameterMetadata.Meta metaBean()
	  {
		return SimpleSurfaceParameterMetadata.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the type of the x-value. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public ValueType XValueType
	  {
		  get
		  {
			return xValueType;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the x-value. </summary>
	  /// <returns> the value of the property </returns>
	  public double XValue
	  {
		  get
		  {
			return xValue;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the type of the y-value. </summary>
	  /// <returns> the value of the property, not null </returns>
	  public ValueType YValueType
	  {
		  get
		  {
			return yValueType;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the y-value. </summary>
	  /// <returns> the value of the property </returns>
	  public double YValue
	  {
		  get
		  {
			return yValue;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  SimpleSurfaceParameterMetadata other = (SimpleSurfaceParameterMetadata) obj;
		  return JodaBeanUtils.equal(xValueType, other.xValueType) && JodaBeanUtils.equal(xValue, other.xValue) && JodaBeanUtils.equal(yValueType, other.yValueType) && JodaBeanUtils.equal(yValue, other.yValue);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(xValueType);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(xValue);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(yValueType);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(yValue);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(160);
		buf.Append("SimpleSurfaceParameterMetadata{");
		buf.Append("xValueType").Append('=').Append(xValueType).Append(',').Append(' ');
		buf.Append("xValue").Append('=').Append(xValue).Append(',').Append(' ');
		buf.Append("yValueType").Append('=').Append(yValueType).Append(',').Append(' ');
		buf.Append("yValue").Append('=').Append(JodaBeanUtils.ToString(yValue));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code SimpleSurfaceParameterMetadata}.
	  /// </summary>
	  public sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  xValueType_Renamed = DirectMetaProperty.ofImmutable(this, "xValueType", typeof(SimpleSurfaceParameterMetadata), typeof(ValueType));
			  xValue_Renamed = DirectMetaProperty.ofImmutable(this, "xValue", typeof(SimpleSurfaceParameterMetadata), Double.TYPE);
			  yValueType_Renamed = DirectMetaProperty.ofImmutable(this, "yValueType", typeof(SimpleSurfaceParameterMetadata), typeof(ValueType));
			  yValue_Renamed = DirectMetaProperty.ofImmutable(this, "yValue", typeof(SimpleSurfaceParameterMetadata), Double.TYPE);
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null, "xValueType", "xValue", "yValueType", "yValue");
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-property for the {@code xValueType} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<ValueType> xValueType_Renamed;
		/// <summary>
		/// The meta-property for the {@code xValue} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<double> xValue_Renamed;
		/// <summary>
		/// The meta-property for the {@code yValueType} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<ValueType> yValueType_Renamed;
		/// <summary>
		/// The meta-property for the {@code yValue} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<double> yValue_Renamed;
		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null, "xValueType", "xValue", "yValueType", "yValue");
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override protected org.joda.beans.MetaProperty<?> metaPropertyGet(String propertyName)
		protected internal override MetaProperty<object> metaPropertyGet(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -868509005: // xValueType
			  return xValueType_Renamed;
			case -777049127: // xValue
			  return xValue_Renamed;
			case -1065022510: // yValueType
			  return yValueType_Renamed;
			case -748419976: // yValue
			  return yValue_Renamed;
		  }
		  return base.metaPropertyGet(propertyName);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends SimpleSurfaceParameterMetadata> builder()
		public override BeanBuilder<SimpleSurfaceParameterMetadata> builder()
		{
		  return new SimpleSurfaceParameterMetadata.Builder();
		}

		public override Type beanType()
		{
		  return typeof(SimpleSurfaceParameterMetadata);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// The meta-property for the {@code xValueType} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<ValueType> xValueType()
		{
		  return xValueType_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code xValue} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<double> xValue()
		{
		  return xValue_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code yValueType} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<ValueType> yValueType()
		{
		  return yValueType_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code yValue} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<double> yValue()
		{
		  return yValue_Renamed;
		}

		//-----------------------------------------------------------------------
		protected internal override object propertyGet(Bean bean, string propertyName, bool quiet)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -868509005: // xValueType
			  return ((SimpleSurfaceParameterMetadata) bean).XValueType;
			case -777049127: // xValue
			  return ((SimpleSurfaceParameterMetadata) bean).XValue;
			case -1065022510: // yValueType
			  return ((SimpleSurfaceParameterMetadata) bean).YValueType;
			case -748419976: // yValue
			  return ((SimpleSurfaceParameterMetadata) bean).YValue;
		  }
		  return base.propertyGet(bean, propertyName, quiet);
		}

		protected internal override void propertySet(Bean bean, string propertyName, object newValue, bool quiet)
		{
		  metaProperty(propertyName);
		  if (quiet)
		  {
			return;
		  }
		  throw new System.NotSupportedException("Property cannot be written: " + propertyName);
		}

	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code SimpleSurfaceParameterMetadata}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<SimpleSurfaceParameterMetadata>
	  {

		internal ValueType xValueType;
		internal double xValue;
		internal ValueType yValueType;
		internal double yValue;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -868509005: // xValueType
			  return xValueType;
			case -777049127: // xValue
			  return xValue;
			case -1065022510: // yValueType
			  return yValueType;
			case -748419976: // yValue
			  return yValue;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		}

		public override Builder set(string propertyName, object newValue)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -868509005: // xValueType
			  this.xValueType = (ValueType) newValue;
			  break;
			case -777049127: // xValue
			  this.xValue = (double?) newValue.Value;
			  break;
			case -1065022510: // yValueType
			  this.yValueType = (ValueType) newValue;
			  break;
			case -748419976: // yValue
			  this.yValue = (double?) newValue.Value;
			  break;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		  return this;
		}

		public override SimpleSurfaceParameterMetadata build()
		{
		  return new SimpleSurfaceParameterMetadata(xValueType, xValue, yValueType, yValue);
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  StringBuilder buf = new StringBuilder(160);
		  buf.Append("SimpleSurfaceParameterMetadata.Builder{");
		  buf.Append("xValueType").Append('=').Append(JodaBeanUtils.ToString(xValueType)).Append(',').Append(' ');
		  buf.Append("xValue").Append('=').Append(JodaBeanUtils.ToString(xValue)).Append(',').Append(' ');
		  buf.Append("yValueType").Append('=').Append(JodaBeanUtils.ToString(yValueType)).Append(',').Append(' ');
		  buf.Append("yValue").Append('=').Append(JodaBeanUtils.ToString(yValue));
		  buf.Append('}');
		  return buf.ToString();
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}