using System;
using System.Collections.Generic;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.basics.date
{
//JAVA TO C# CONVERTER TODO TASK: This Java 'import static' statement cannot be converted to C#:
//	import static com.opengamma.strata.basics.date.LocalDateUtils.plusDays;


	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	using ArgChecker = com.opengamma.strata.collect.ArgChecker;

	/// <summary>
	/// A holiday calendar implementation that has no holidays.
	/// <para>
	/// This immutable implementation of <seealso cref="HolidayCalendar"/> treats all days as valid business days.
	/// </para>
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") final class NoHolidaysCalendar implements HolidayCalendar, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	internal sealed class NoHolidaysCalendar : HolidayCalendar, ImmutableBean
	{
	  // methods are overridden from default implementations to gain performance

	  /// <summary>
	  /// The singleton instance.
	  /// </summary>
	  internal static readonly NoHolidaysCalendar INSTANCE = new NoHolidaysCalendar();

	  // resolve after deserialization
	  private object readResolve()
	  {
		return INSTANCE;
	  }

	  //-------------------------------------------------------------------------
	  public HolidayCalendarId Id
	  {
		  get
		  {
			return HolidayCalendarIds.NO_HOLIDAYS;
		  }
	  }

	  public bool isHoliday(LocalDate date)
	  {
		return false;
	  }

	  public override bool isBusinessDay(LocalDate date)
	  {
		return true;
	  }

	  public override LocalDate shift(LocalDate date, int amount)
	  {
		return plusDays(date, amount);
	  }

	  public override LocalDate next(LocalDate date)
	  {
		return plusDays(date, 1);
	  }

	  public override LocalDate nextOrSame(LocalDate date)
	  {
		return ArgChecker.notNull(date, "date");
	  }

	  public override LocalDate previous(LocalDate date)
	  {
		return plusDays(date, -1);
	  }

	  public override LocalDate previousOrSame(LocalDate date)
	  {
		return ArgChecker.notNull(date, "date");
	  }

	  public override LocalDate nextSameOrLastInMonth(LocalDate date)
	  {
		return ArgChecker.notNull(date, "date");
	  }

	  public override int daysBetween(LocalDate startInclusive, LocalDate endExclusive)
	  {
		return Math.toIntExact(LocalDateUtils.daysBetween(startInclusive, endExclusive));
	  }

	  public override HolidayCalendar combinedWith(HolidayCalendar other)
	  {
		return ArgChecker.notNull(other, "other");
	  }

	  //-------------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		return obj is NoHolidaysCalendar;
	  }

	  public override int GetHashCode()
	  {
		return 1;
	  }

	  public override string ToString()
	  {
		return "HolidayCalendar[NoHolidays]";
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code NoHolidaysCalendar}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static NoHolidaysCalendar.Meta meta()
	  {
		return NoHolidaysCalendar.Meta.INSTANCE;
	  }

	  static NoHolidaysCalendar()
	  {
		MetaBean.register(NoHolidaysCalendar.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private NoHolidaysCalendar()
	  {
	  }

	  public override NoHolidaysCalendar.Meta metaBean()
	  {
		return NoHolidaysCalendar.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code NoHolidaysCalendar}.
	  /// </summary>
	  internal sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null);
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null);
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends NoHolidaysCalendar> builder()
		public override BeanBuilder<NoHolidaysCalendar> builder()
		{
		  return new NoHolidaysCalendar.Builder();
		}

		public override Type beanType()
		{
		  return typeof(NoHolidaysCalendar);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code NoHolidaysCalendar}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<NoHolidaysCalendar>
	  {

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  throw new NoSuchElementException("Unknown property: " + propertyName);
		}

		public override Builder set(string propertyName, object newValue)
		{
		  throw new NoSuchElementException("Unknown property: " + propertyName);
		}

		public override NoHolidaysCalendar build()
		{
		  return new NoHolidaysCalendar();
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  return "NoHolidaysCalendar.Builder{}";
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}