using System;
using System.Collections.Generic;
using System.Text;

/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
namespace com.opengamma.strata.product.rate
{

	using Bean = org.joda.beans.Bean;
	using BeanBuilder = org.joda.beans.BeanBuilder;
	using ImmutableBean = org.joda.beans.ImmutableBean;
	using JodaBeanUtils = org.joda.beans.JodaBeanUtils;
	using MetaBean = org.joda.beans.MetaBean;
	using MetaProperty = org.joda.beans.MetaProperty;
	using BeanDefinition = org.joda.beans.gen.BeanDefinition;
	using PropertyDefinition = org.joda.beans.gen.PropertyDefinition;
	using DirectMetaBean = org.joda.beans.impl.direct.DirectMetaBean;
	using DirectMetaProperty = org.joda.beans.impl.direct.DirectMetaProperty;
	using DirectMetaPropertyMap = org.joda.beans.impl.direct.DirectMetaPropertyMap;
	using DirectPrivateBeanBuilder = org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

	using ImmutableSet = com.google.common.collect.ImmutableSet;
	using Index = com.opengamma.strata.basics.index.Index;
	using PriceIndex = com.opengamma.strata.basics.index.PriceIndex;
	using PriceIndexObservation = com.opengamma.strata.basics.index.PriceIndexObservation;
	using ArgChecker = com.opengamma.strata.collect.ArgChecker;

	/// <summary>
	/// Defines the computation of inflation figures from a price index
	/// where the start index value is known.
	/// <para>
	/// A typical application of this rate computation is payments of a capital indexed bond, 
	/// where the reference start month is start month of the bond rather than start month of the payment period.
	/// </para>
	/// <para>
	/// A price index is typically published monthly and has a delay before publication.
	/// The rate observed by this instance will be based on the start index value
	/// and the observation relative to the end month.
	/// </para>
	/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @BeanDefinition(builderScope = "private") public final class InflationEndMonthRateComputation implements RateComputation, org.joda.beans.ImmutableBean, java.io.Serializable
	[Serializable]
	public sealed class InflationEndMonthRateComputation : RateComputation, ImmutableBean
	{
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "ArgChecker.notNegativeOrZero") private final double startIndexValue;
		private readonly double startIndexValue;
	  /// <summary>
	  /// The observation at the end.
	  /// <para>
	  /// The inflation rate is the ratio between the start index value and end observation.
	  /// The end month is typically three months before the end of the period.
	  /// </para>
	  /// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @PropertyDefinition(validate = "notNull") private final com.opengamma.strata.basics.index.PriceIndexObservation endObservation;
	  private readonly PriceIndexObservation endObservation;

	  //-------------------------------------------------------------------------
	  /// <summary>
	  /// Creates an instance from an index, start index value and reference end month.
	  /// </summary>
	  /// <param name="index">  the index </param>
	  /// <param name="startIndexValue">  the start index value </param>
	  /// <param name="referenceEndMonth">  the reference end month </param>
	  /// <returns> the inflation rate computation </returns>
	  public static InflationEndMonthRateComputation of(PriceIndex index, double startIndexValue, YearMonth referenceEndMonth)
	  {

		return new InflationEndMonthRateComputation(startIndexValue, PriceIndexObservation.of(index, referenceEndMonth));
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the Price index.
	  /// </summary>
	  /// <returns> the Price index </returns>
	  public PriceIndex Index
	  {
		  get
		  {
			return endObservation.Index;
		  }
	  }

	  //-------------------------------------------------------------------------
	  public void collectIndices(ImmutableSet.Builder<Index> builder)
	  {
		builder.add(Index);
	  }

	  //------------------------- AUTOGENERATED START -------------------------
	  /// <summary>
	  /// The meta-bean for {@code InflationEndMonthRateComputation}. </summary>
	  /// <returns> the meta-bean, not null </returns>
	  public static InflationEndMonthRateComputation.Meta meta()
	  {
		return InflationEndMonthRateComputation.Meta.INSTANCE;
	  }

	  static InflationEndMonthRateComputation()
	  {
		MetaBean.register(InflationEndMonthRateComputation.Meta.INSTANCE);
	  }

	  /// <summary>
	  /// The serialization version id.
	  /// </summary>
	  private const long serialVersionUID = 1L;

	  private InflationEndMonthRateComputation(double startIndexValue, PriceIndexObservation endObservation)
	  {
		ArgChecker.notNegativeOrZero(startIndexValue, "startIndexValue");
		JodaBeanUtils.notNull(endObservation, "endObservation");
		this.startIndexValue = startIndexValue;
		this.endObservation = endObservation;
	  }

	  public override InflationEndMonthRateComputation.Meta metaBean()
	  {
		return InflationEndMonthRateComputation.Meta.INSTANCE;
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the start index value.
	  /// <para>
	  /// The published index value of the start month.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property </returns>
	  public double StartIndexValue
	  {
		  get
		  {
			return startIndexValue;
		  }
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// Gets the observation at the end.
	  /// <para>
	  /// The inflation rate is the ratio between the start index value and end observation.
	  /// The end month is typically three months before the end of the period.
	  /// </para>
	  /// </summary>
	  /// <returns> the value of the property, not null </returns>
	  public PriceIndexObservation EndObservation
	  {
		  get
		  {
			return endObservation;
		  }
	  }

	  //-----------------------------------------------------------------------
	  public override bool Equals(object obj)
	  {
		if (obj == this)
		{
		  return true;
		}
		if (obj != null && obj.GetType() == this.GetType())
		{
		  InflationEndMonthRateComputation other = (InflationEndMonthRateComputation) obj;
		  return JodaBeanUtils.equal(startIndexValue, other.startIndexValue) && JodaBeanUtils.equal(endObservation, other.endObservation);
		}
		return false;
	  }

	  public override int GetHashCode()
	  {
		int hash = this.GetType().GetHashCode();
		hash = hash * 31 + JodaBeanUtils.GetHashCode(startIndexValue);
		hash = hash * 31 + JodaBeanUtils.GetHashCode(endObservation);
		return hash;
	  }

	  public override string ToString()
	  {
		StringBuilder buf = new StringBuilder(96);
		buf.Append("InflationEndMonthRateComputation{");
		buf.Append("startIndexValue").Append('=').Append(startIndexValue).Append(',').Append(' ');
		buf.Append("endObservation").Append('=').Append(JodaBeanUtils.ToString(endObservation));
		buf.Append('}');
		return buf.ToString();
	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The meta-bean for {@code InflationEndMonthRateComputation}.
	  /// </summary>
	  public sealed class Meta : DirectMetaBean
	  {
		  internal bool InstanceFieldsInitialized = false;

		  internal void InitializeInstanceFields()
		  {
			  startIndexValue_Renamed = DirectMetaProperty.ofImmutable(this, "startIndexValue", typeof(InflationEndMonthRateComputation), Double.TYPE);
			  endObservation_Renamed = DirectMetaProperty.ofImmutable(this, "endObservation", typeof(InflationEndMonthRateComputation), typeof(PriceIndexObservation));
			  metaPropertyMap$ = new DirectMetaPropertyMap(this, null, "startIndexValue", "endObservation");
		  }

		/// <summary>
		/// The singleton instance of the meta-bean.
		/// </summary>
		internal static readonly Meta INSTANCE = new Meta();

		/// <summary>
		/// The meta-property for the {@code startIndexValue} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<double> startIndexValue_Renamed;
		/// <summary>
		/// The meta-property for the {@code endObservation} property.
		/// </summary>
//JAVA TO C# CONVERTER NOTE: Fields cannot have the same name as methods:
		internal MetaProperty<PriceIndexObservation> endObservation_Renamed;
		/// <summary>
		/// The meta-properties.
		/// </summary>
//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: private final java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap$ = new org.joda.beans.impl.direct.DirectMetaPropertyMap(this, null, "startIndexValue", "endObservation");
		internal IDictionary<string, MetaProperty<object>> metaPropertyMap$;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Meta()
		{
			if (!InstanceFieldsInitialized)
			{
				InitializeInstanceFields();
				InstanceFieldsInitialized = true;
			}
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override protected org.joda.beans.MetaProperty<?> metaPropertyGet(String propertyName)
		protected internal override MetaProperty<object> metaPropertyGet(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -1656407615: // startIndexValue
			  return startIndexValue_Renamed;
			case 82210897: // endObservation
			  return endObservation_Renamed;
		  }
		  return base.metaPropertyGet(propertyName);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public org.joda.beans.BeanBuilder<? extends InflationEndMonthRateComputation> builder()
		public override BeanBuilder<InflationEndMonthRateComputation> builder()
		{
		  return new InflationEndMonthRateComputation.Builder();
		}

		public override Type beanType()
		{
		  return typeof(InflationEndMonthRateComputation);
		}

//JAVA TO C# CONVERTER WARNING: Java wildcard generics have no direct equivalent in .NET:
//ORIGINAL LINE: @Override public java.util.Map<String, org.joda.beans.MetaProperty<?>> metaPropertyMap()
		public override IDictionary<string, MetaProperty<object>> metaPropertyMap()
		{
		  return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/// <summary>
		/// The meta-property for the {@code startIndexValue} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<double> startIndexValue()
		{
		  return startIndexValue_Renamed;
		}

		/// <summary>
		/// The meta-property for the {@code endObservation} property. </summary>
		/// <returns> the meta-property, not null </returns>
		public MetaProperty<PriceIndexObservation> endObservation()
		{
		  return endObservation_Renamed;
		}

		//-----------------------------------------------------------------------
		protected internal override object propertyGet(Bean bean, string propertyName, bool quiet)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -1656407615: // startIndexValue
			  return ((InflationEndMonthRateComputation) bean).StartIndexValue;
			case 82210897: // endObservation
			  return ((InflationEndMonthRateComputation) bean).EndObservation;
		  }
		  return base.propertyGet(bean, propertyName, quiet);
		}

		protected internal override void propertySet(Bean bean, string propertyName, object newValue, bool quiet)
		{
		  metaProperty(propertyName);
		  if (quiet)
		  {
			return;
		  }
		  throw new System.NotSupportedException("Property cannot be written: " + propertyName);
		}

	  }

	  //-----------------------------------------------------------------------
	  /// <summary>
	  /// The bean-builder for {@code InflationEndMonthRateComputation}.
	  /// </summary>
	  private sealed class Builder : DirectPrivateBeanBuilder<InflationEndMonthRateComputation>
	  {

		internal double startIndexValue;
		internal PriceIndexObservation endObservation;

		/// <summary>
		/// Restricted constructor.
		/// </summary>
		internal Builder()
		{
		}

		//-----------------------------------------------------------------------
		public override object get(string propertyName)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -1656407615: // startIndexValue
			  return startIndexValue;
			case 82210897: // endObservation
			  return endObservation;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		}

		public override Builder set(string propertyName, object newValue)
		{
		  switch (propertyName.GetHashCode())
		  {
			case -1656407615: // startIndexValue
			  this.startIndexValue = (double?) newValue.Value;
			  break;
			case 82210897: // endObservation
			  this.endObservation = (PriceIndexObservation) newValue;
			  break;
			default:
			  throw new NoSuchElementException("Unknown property: " + propertyName);
		  }
		  return this;
		}

		public override InflationEndMonthRateComputation build()
		{
		  return new InflationEndMonthRateComputation(startIndexValue, endObservation);
		}

		//-----------------------------------------------------------------------
		public override string ToString()
		{
		  StringBuilder buf = new StringBuilder(96);
		  buf.Append("InflationEndMonthRateComputation.Builder{");
		  buf.Append("startIndexValue").Append('=').Append(JodaBeanUtils.ToString(startIndexValue)).Append(',').Append(' ');
		  buf.Append("endObservation").Append('=').Append(JodaBeanUtils.ToString(endObservation));
		  buf.Append('}');
		  return buf.ToString();
		}

	  }

	  //-------------------------- AUTOGENERATED END --------------------------
	}

}